"""comments

Revision ID: 4516a7b3c930
Revises: fa08682a0e23
Create Date: 2026-03-20 09:53:28.202667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4516a7b3c930'
down_revision: Union[str, Sequence[str], None] = 'fa08682a0e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute("UPDATE comments SET movie_id=null WHERE answer_to IS NOT NULL ")
    op.create_check_constraint(
        "check_comment_target",
        "comments",
        "NOT (movie_id IS NULL AND answer_to IS NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Удаляем constraint
    op.drop_constraint("check_comment_target", "comments", type_="check")

    # Обновляем комментарии с NULL movie_id, присваивая им movie_id родительского комментария (рекурсивно)
    # Используем рекурсивный CTE, чтобы поднять movie_id из корневого комментария
    op.execute("""
        WITH RECURSIVE comment_tree AS (
            -- Базовый уровень: все комментарии, у которых movie_id не NULL (корни)
            SELECT id, movie_id, answer_to
            FROM comments
            WHERE movie_id IS NOT NULL
            UNION ALL
            -- Рекурсивно: комментарии, у которых movie_id IS NULL, связываем с родителем
            SELECT c.id, ct.movie_id, c.answer_to
            FROM comments c
            JOIN comment_tree ct ON c.answer_to = ct.id
            WHERE c.movie_id IS NULL
        )
        UPDATE comments
        SET movie_id = ct.movie_id
        FROM comment_tree ct
        WHERE comments.id = ct.id
        AND comments.movie_id IS NULL;
    """)

    # Возвращаем столбцу свойство NOT NULL
    op.alter_column('comments', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###