"""constraints

Revision ID: 95985e696916
Revises: 55d34cf79984
Create Date: 2026-01-24 15:38:18.438719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from backend.src.films.domain.entities.constants import MovieType, Genre, Profession

# revision identifiers, used by Alembic.
revision: str = '95985e696916'
down_revision: Union[str, Sequence[str], None] = '55d34cf79984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

types = [{"id": int(mt), "name": str(mt)} for mt in MovieType]
genres = [{"name": str(genre)} for genre in Genre]
professions = [{"name": str(profession)} for profession in Profession]


def upgrade() -> None:
    """Upgrade schema."""
    op.bulk_insert(
        table=sa.table(
            "types",
            sa.column("id", sa.Integer),
            sa.column("name", sa.String),
        ),
        rows=types,
    )

    op.bulk_insert(
        table=sa.table("genres", sa.column("name", sa.String)),
        rows=genres,
    )

    op.bulk_insert(
        table=sa.table("professions", sa.column("name", sa.String)),
        rows=professions,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE FROM types WHERE id in {tuple(t["id"] for t in types)}")
    op.execute(f"DELETE FROM genres WHERE name in {tuple(g["name"] for g in genres)}")
    op.execute(f"DELETE FROM professions WHERE name in {tuple(p["name"] for p in professions)}")
    # ### end Alembic commands ###
