"""is_blocked removed

Revision ID: bda64f3e934e
Revises: cd9a61b5f28f
Create Date: 2026-01-16 10:46:21.017151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda64f3e934e'
down_revision: Union[str, Sequence[str], None] = 'cd9a61b5f28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movie_group')
    op.add_column('movies', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movies', 'related_groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.add_column('related_groups', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('related_groups', 'name')
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'group_id')
    op.create_table('movie_group',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('movie_group_movie_id_fkey')),
    sa.ForeignKeyConstraint(['related_group_id'], ['related_groups.id'], name=op.f('movie_group_related_group_id_fkey')),
    sa.PrimaryKeyConstraint('movie_id', 'related_group_id', name=op.f('movie_group_pkey'))
    )
    op.drop_table('blockings')
    # ### end Alembic commands ###
