"""internal

Revision ID: cd9a61b5f28f
Revises: a9eb39069395
Create Date: 2026-01-08 11:11:57.854584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9a61b5f28f'
down_revision: Union[str, Sequence[str], None] = 'a9eb39069395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('votes_sum', sa.Integer(), server_default='0', nullable=False))
    op.add_column('movies', sa.Column('votes_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('movies', 'internal_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('internal_rating', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.drop_column('movies', 'votes_count')
    op.drop_column('movies', 'votes_sum')
    # ### end Alembic commands ###
