"""rename

Revision ID: edd7f504f8f9
Revises: 4516a7b3c930
Create Date: 2026-03-20 16:19:08.017883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'edd7f504f8f9'
down_revision: Union[str, Sequence[str], None] = '4516a7b3c930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_reactions', sa.Column('reaction', sa.Boolean(), nullable=False))
    op.drop_column('comment_reactions', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_reactions',
                  sa.Column('rating', sa.BOOLEAN(), autoincrement=False, nullable=False, default=True))
    op.drop_column('comment_reactions', 'reaction')
    # ### end Alembic commands ###
