"""indexes

Revision ID: f333cff8fc23
Revises: 7a7b1c239c42
Create Date: 2026-01-22 16:56:22.884645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f333cff8fc23'
down_revision: Union[str, Sequence[str], None] = '7a7b1c239c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_blockings_user_ends_at', 'blockings', ['user_id', 'ends_at'], unique=False)
    op.create_index('idx_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('idx_comments_thread', 'comments', ['answer_to', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_answer_to'), 'comments', ['answer_to'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_constraint(op.f('confirmations_user_id_key'), 'confirmations', type_='unique')
    op.create_index(op.f('ix_confirmations_user_id'), 'confirmations', ['user_id'], unique=True)
    op.drop_constraint(op.f('countries_name_key'), 'countries', type_='unique')
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_index(op.f('ix_lists_is_public'), 'lists', ['is_public'], unique=False)
    op.create_index(op.f('ix_lists_user_id'), 'lists', ['user_id'], unique=False)
    op.add_column('movies', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('russian', coalesce(name, '')), 'A') || \n            setweight(to_tsvector('russian', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False))
    op.create_index('idx_movies_search', 'movies', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_movies_group_id'), 'movies', ['group_id'], unique=False)
    op.create_index(op.f('ix_movies_is_series'), 'movies', ['is_series'], unique=False)
    op.create_index(op.f('ix_movies_kp_rating'), 'movies', ['kp_rating'], unique=False)
    op.create_index(op.f('ix_movies_name'), 'movies', ['name'], unique=False)
    op.create_index(op.f('ix_movies_type_id'), 'movies', ['type_id'], unique=False)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    op.create_index(op.f('ix_user_ratings_rating'), 'user_ratings', ['rating'], unique=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_ratings_rating'), table_name='user_ratings')
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_type_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_name'), table_name='movies')
    op.drop_index(op.f('ix_movies_kp_rating'), table_name='movies')
    op.drop_index(op.f('ix_movies_is_series'), table_name='movies')
    op.drop_index(op.f('ix_movies_group_id'), table_name='movies')
    op.drop_index('idx_movies_search', table_name='movies', postgresql_using='gin')
    op.drop_column('movies', 'search_vector')
    op.drop_index(op.f('ix_lists_user_id'), table_name='lists')
    op.drop_index(op.f('ix_lists_is_public'), table_name='lists')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.create_unique_constraint(op.f('countries_name_key'), 'countries', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_confirmations_user_id'), table_name='confirmations')
    op.create_unique_constraint(op.f('confirmations_user_id_key'), 'confirmations', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_answer_to'), table_name='comments')
    op.drop_index('idx_comments_thread', table_name='comments')
    op.drop_index('idx_comments_created_at', table_name='comments')
    op.drop_index('idx_blockings_user_ends_at', table_name='blockings')
    # ### end Alembic commands ###
