"""birthday_null

Revision ID: fa08682a0e23
Revises: 95985e696916
Create Date: 2026-03-18 07:59:18.020460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa08682a0e23'
down_revision: Union[str, Sequence[str], None] = '95985e696916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('person_movie', sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DELETE FROM persons where birthday is NULL")
    op.alter_column('persons', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('person_movie', 'description')

    # ### end Alembic commands ###
