name: Lint and test
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Create .env file
        run: touch .env

      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test_environment

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DATABASE_NAME=${{ vars.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ vars.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ vars.DATABASE_PASSWORD }}" >> .env
          echo "EMAIL=${{ vars.EMAIL }}" >> .env

      - name: Activate entrypoint
        run: chmod +x backend/entrypoint.sh localstack-init.sh

      - name: Run in Docker
        run: docker compose up --build -d

      - name: Wait for containers
        run: sleep 20

      - name: Test
        run: make test
